name: Deploy Go Backend to Google Cloud Run

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

env:
  PROJECT_ID: media-server-465705
  REGION: us-central1
  SERVICE_NAME: media-server
  REPO_NAME: media-server-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        working-directory: ./media-server
        run: |
          IMAGE_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Deploy to Cloud Run
        working-directory: ./media-server
        run: |
          IMAGE_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=$IMAGE_TAG \
            --region=${{ env.REGION }} \
            --platform=managed \
            --quiet
